somesystem:
  client:
#    host: 172.17.1.49
    host: localhost
    port: 8080
    timeout: 10000
    http: HTTP

grpc:
  client:
#    host: 172.17.1.49
    host: localhost
    port: 15001
  server:
    port: 15001
